# conda 环境配置
conda:
  python: python3.12
  fastqc: basic
  multiqc: basic
  fastp: basic2
  bwa: basic
  samtools: basic
  bcftools: basic
  gatk: basic
  lofreq: basic

# 线程数配置
threads:
  low: 4
  medium: 8
  high: 16

# 数据库配置
database:
  # 参考基因组, 需要提前建 bwa/samtools/picard 索引
  hg19: /data/mengxf/Database/reference/hg19/hg19.fa
